spring:
  application:
    name: quirinda-devtech-auth
  security:
    user:
      name: admin
      password: admin123
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db # Replace with your DB URL
    username: postgres # Replace with your DB username
    password: postgres # Replace with your DB password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the schema
    show-sql: true

server:
  port: 8080

jwt:
  secret: QuirindasDevTechSecretKeyForAuthenticationAndAuthorization123456
  expiration: 86400000

logging:
  level:
    root: INFO
    com.quirinda: DEBUG
